export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const SET_USER = "SET_USER";
export const EMPTY_BASKET = "EMPTY_BASKET";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT";

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GENERATE_PAYMENT_SECRET = 'GENERATE_PAYMENT_SECRET';
export const SET_PAYMENT_SECRET = 'SET_PAYMENT_SECRET';

export const SAVE_ORDER_SUCCESS = 'SAVE_ORDER_SUCCESS';
export const SAVE_ORDER_FAIL = 'SAVE_ORDER_FAIL';
export const SET_USER_ORDERS = 'SET_USER_ORDERS';
export const FETCH_USER_ORDERS_FAIL = 'FETCH_USER_ORDERS_FAIL';
export const RESET_SUCCEEDED = 'RESET_SUCCEEDED';


