export const productsData = [
  {
    id: Math.floor(Math.random() * 1000) + 1,
    title: "Mastering HTML, CSS & Javascript Web Publishing",
    price: 19.99,
    image: "https://m.media-amazon.com/images/I/61DnYrf3vdL._AC_UY218_.jpg",
    rating: 4,
    details: [
      "In just one hour a day, you’ll learn the skills you need to design, create and maintain a professional-looking website",
      "No previous experience required. By following each short, one-hour lesson in this book, anyone can learn the basics of web development.",
      "Learn at your own pace. You can work through each lesson sequentially to make sure you thoroughly understand all the concepts and methodologies, or you can focus on specific lessons to learn the techniques that interest you most.",
      "Fully implement the HTML5 and CSS3 standards",
    ],
  },
  {
    id: Math.floor(Math.random() * 1000) + 1,
    title:
      "Apple MacBook Pro (16-inch, 16GB RAM, 512GB Storage, 2.6GHz 9th Gen Intel Core i7) - Space Grey",
    price: 299.99,
    image: "https://m.media-amazon.com/images/I/71L2iBSyyOL._AC_UY218_.jpg",
    rating: 3,
    details: [
      "Stunning 16-inch Retina display with True Tone technology",
      "AMD Radeon Pro 5300M graphics with GDDR6 memory",
      "Ninth-generation 6-core Intel Core i7 processor",
      'Up to 11 hours of battery life',
      "Intel UHD Graphics 630",
      "Six-speaker system with force-cancelling woofers",
    ],
  },
  {
    id: Math.floor(Math.random() * 1000) + 1,
    title: "The Palace of Illusions: 10th Anniversary Edition",
    price: 11.99,
    image: "https://m.media-amazon.com/images/I/A1dtQ-soQEL._AC_UY218_.jpg",
    rating: 3,
    details: [
      "Be taken back to a time that is half history, half myth, and wholly magical..",
      "First published in 2008, Chitra Banerjee Divakaruni's The Palace of Illusions has received wide acclaim for giving a woman's take on the timeless tale that is the Mahabharata",
      "This tenth anniversary edition, complete with a new author’s note, celebrates once again a remarkable and deeply human story about a woman born into a man’s world",
    ],
  },
  {
    id: Math.floor(Math.random() * 1000) + 1,
    title: "Echo Dot (3rd Gen) – Smart speaker with Alexa (Black)",
    price: 99.99,
    image: "https://m.media-amazon.com/images/I/61EXU8BuGZL._AC_UY218_.jpg",
    rating: 4,
    details: [
      "Stream millions of songs from Amazon Prime Music, Spotify, JioSaavn, Gaana, and Apple Music",
      "Just ask Alexa for music, news, trivia, scores, weather, alarms, kids rhymes and stories",
      "Echo Dot is a smart speaker that can be operated by voice, is compact and can fit in your favorite places",
      "Make your home smart with Alexa and use voice to control lights, ACs, TVs, geysers, water motors and more. You can purchase smart lights, plugs and other accessories separately",
    ],
  },
  {
    id: Math.floor(Math.random() * 1000) + 1,
    title:
      "boAt Bassheads 225 in Ear Wired Earphones with Mic(Black)",
    price: 79.99,
    image: "https://m.media-amazon.com/images/I/719elVA3FvL._AC_UY218_.jpg",
    rating: 4,
    details: [
      'Has a PVC cable which is durable and tangle free',
      "Compatibility and Connectivity: Compatible with Android/iOS and connectivity via 3.5mm AUX cable",
      "Mic: In line Mic",
      "Other Inclusions: Additional earbuds, Warranty Card",
    ],
  },
  {
    id: Math.floor(Math.random() * 1000) + 1,
    title:
      "Redmi Smart Band - Black (Direct USB Charging, Works with Xiaomi Wear App)",
    price: 49.99,
    image: "https://m.media-amazon.com/images/I/71RrPTCdy-L._AC_UY218_.jpg",
    rating: 3,
    details: [
      "Direct USB Charging: No need to carry charger around; Hassle-free charging with in-built USB connector",
      '1.08" (2.74 cm) Full touch Color display; Adjustable screen brightness and dynamic display. Full touchscreen to make your experience smoother',
      "Long Battery life: Get a long standby time of up to 14 days on a single charge (Standard mode)",
      "24 x7 Heart Rate Monitoring: Track your heart rate in real time and keep your health in check throughout the day.",
      "5ATM Water Resistant: Enjoy you swimming sessions as you can go up to a depth of 50 m for 10 mins",
    ],
  },
  {
    id: Math.floor(Math.random() * 1000) + 1,
    title:
      "Samsung 80 cm (32 inches) Wondertainment Series HD Ready LED Smart TV UA32TE40AAKXXL (Titan Gray)",
    price: 249.99,
    image: "https://m.media-amazon.com/images/I/81cB6pJsTaL._AC_UY218_.jpg",
    rating: 4,
    details: [
      "Connectivity: 2 HDMI ports to connect set top box, Blu Ray players, gaming console | 1 USB ports to connect hard drives and other USB devices",
      "Smart TV Features : Voice Assistants | SmartThings App | Personal Computer | Home Cloud | Live Cast | Screen Share | Music System",
      "Alexa Built-in: Voice control your TV and your day. Just ask Alexa to search for movies, play music, control smart home devices, get sports updates and more",
      "Easy returns: This product is eligible for replacement within 10 days of delivery in case of any product defects, damage or features not matching the description provided",
    ],
  },
  {
    id: Math.floor(Math.random() * 1000) + 1,
    title: "JBL GO Portable Wireless Bluetooth Speaker with Mic (Red)",
    price: 35.99,
    image: "https://m.media-amazon.com/images/I/811-AolfDtL._AC_UY218_.jpg",
    rating: 3,
    details: [
      "JBL Signature Sound",
      "Wireless Bluetooth Streaming",
      "5 Hours of Playtime under optimum audio settings",
      "Long Press Play Button to Activate Google Assistant or Siri",
      "Noise-cancelling Speakerphone",
      "Audio Cable Input",
      "1 year manufacturer’s warranty",
    ],
  },
  {
    id: Math.floor(Math.random() * 1000) + 1,
    title: "Quantum QHM7468 USB Gamepad with Dual Vibration (Black)",
    price: 29.99,
    image: "https://m.media-amazon.com/images/I/51NiAnW7nRL._AC_UY218_.jpg",
    rating: 3,
    details: [
      "Remote joystick QHM 7468-2VA is engineered to perfection and is black in colour",
      "The game controller by Quantum has a soft touch and is easy to hold. It is made with high quality ABS plastic material which is sturdy enough for your tough gaming sessions",
      "The game controller is perfectly designed to fit snugly in your hands and ensures long-term use without any fail",
      "Quantum’s gaming mouse comes with a vast spectrum of 8 fire buttons and 4 Axis control for an intense gaming environment",
    ],
  },
];
